import {
  Mail,
  Phone,
  Globe,
  Linkedin,
  Github,
  Download,
  Code2,
  Cloud,
  Database,
  Settings,
  Brain,
  Users,
  RotateCcw,
  Rocket,
  GraduationCap,
  Award,
  BookOpen,
  ExternalLink,
  Laptop,
  Bot,
  Lock,
  Clock,
  MapPin,
  Home,
  Info,
  Briefcase,
  Menu,
  Search,
  ImageIcon,
  Palette,
  Languages,
  FolderTree,
  Activity,
  Network,
  PanelBottom,
  User,
  Heart,
  Send,
  Coffee,
  Zap,
  Shield,
  Server,
  GitBranch,
  Star,
} from "lucide-react";

export const ICONS = {
  mail: Mail,
  phone: Phone,
  globe: Globe,
  linkedin: Linkedin,
  github: Github,
  download: Download,
  code: Code2,
  cloud: Cloud,
  database: Database,
  settings: Settings,
  brain: Brain,
  users: Users,
  rotate: RotateCcw,
  rocket: Rocket,
  graduation: GraduationCap,
  award: Award,
  book: BookOpen,
  externalLink: ExternalLink,
  laptop: Laptop,
  bot: Bot,
  lock: Lock,
  clock: Clock,
  mapPin: MapPin,
  home: Home,
  info: Info,
  briefcase: Briefcase,
  menu: Menu,
  search: Search,
  image: ImageIcon,
  palette: Palette,
  languages: Languages,
  download2: Download,
  folderTree: FolderTree,
  activity: Activity,
  network: Network,
  panelBottom: PanelBottom,
  user: User,
  heart: Heart,
  send: Send,
  coffee: Coffee,
  zap: Zap,
  shield: Shield,
  server: Server,
  gitBranch: GitBranch,
  star: Star,
} as const;

export type IconName = keyof typeof ICONS;

export function resolveIcon(name: string) {
  return ICONS[name as IconName] ?? ICONS.code;
}

export const ICON_NAMES = Object.keys(ICONS) as IconName[];
